from turtle import *

import random

a=Turtle()
a.color('blue')
a.shape('turtle')
a.penup()
a.goto(-160,100)
a.penup()
b=Turtle()
b.color('violet')
b.shape('turtle')
b.penup()
b.goto(-160,80)
b.penup()
c=Turtle()
c.color('indigo')
c.shape('turtle')
c.penup()
c.goto(-160,60)
c.penup()
d=Turtle()
d.color('green')
d.shape('turtle')
d.penup()
d.goto(-160,40)
d.penup()
e=Turtle()
e.color('yellow')
e.shape('turtle')
e.penup()
e.goto(-160,20)
e.penup()
f=Turtle()
f.color('red')
f.shape('turtle')
f.penup()
f.goto(-160,0)
f.penup()
penup()
goto(-140,140)


for i in range (11):
  write(i,align='center')
  right(90)
  forward(10)
  pendown()
  forward(150)
  penup()
  backward(160)
  left(90)
  forward(20)
  
speed(10)
penup()
goto(-140,140)
for j in range(100):
  a.forward(random.randint(1,3))
  b.forward(random.randint(1,3))
  c.forward(random.randint(1,3))
  d.forward(random.randint(1,3))
  e.forward(random.randint(1,3))
  f.forward(random.randint(1,3))


